# Generated by Django 4.1.4 on 2023-01-29 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_token",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                max_length=255,
                null=True,
                verbose_name="email token",
            ),
        ),
    ]
