# Generated by Django 4.1.7 on 2023-02-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0004_state"),
        ("customauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chatroom.country",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chatroom.state",
            ),
        ),
    ]
