# Generated by Django 4.1.4 on 2023-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0003_alter_user_email_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Active Status"),
        ),
    ]
