# Generated by Django 4.1.4 on 2022-12-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("category", "name")},
        ),
    ]
