# Generated by Django 4.1.4 on 2022-12-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0002_alter_subcategory_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="max_previous_message",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="max_user",
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_categories",
                to="chatroom.category",
            ),
        ),
    ]
