# Generated by Django 4.1.4 on 2022-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0005_country_category_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
