# Generated by Django 4.1.7 on 2023-03-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0005_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="country",
            name="ordering",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="ordering",
        ),
    ]
