# Generated by Django 4.1.7 on 2023-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0006_alter_country_options_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
