# Generated by Django 4.1.7 on 2023-03-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0007_country_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chatroom",
                to="chatroom.country",
            ),
        ),
    ]
