# Generated by Django 4.1.7 on 2023-03-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0009_alter_directmessageuser_friend_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessageuser",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
